name: pepp-ld-tdn
channels:
  - conda-forge
dependencies:
  - python=3.11
  - scipy
  - pyyaml
  - ripser
  - seaborn
  - freud
  - numpy
  - tqdm
  - joblib
  - mdanalysis
  - tensorboard
  - matplotlib
  - pandas
  - h5py
  - scikit-learn
  - ruff
  - black
  - ase
  - rdkit
  - openbabel
